name: todey
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl:
  flutter_icons: ^1.1.0
  toast: ^0.1.5
  get:
  flutter_screenutil: 
  shared_preferences: ^2.0.8
  firebase_core:
  firebase_auth:
  google_sign_in:
  sqflite:
  fl_chart: 
  path_provider:
  feedback: 
  syncfusion_flutter_datepicker:
  flutter_local_notifications: ^9.1.1
  cached_network_image:
  url_launcher: ^6.0.12
  flutter_phoenix:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
  - family: MADType
    fonts:
    - asset: assets/fonts/Abel-Regular.ttf
  - family: Raleway
    fonts:
    - asset: assets/fonts/Raleway-Black.ttf
