name: todey
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  intl: ^0.17.0
  get: ^4.6.1
  flutter_screenutil: ^5.0.2 
  shared_preferences: ^2.0.11
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  google_sign_in: ^5.2.1
  sqflite: ^2.0.1
  #  fl_chart: 
  path_provider: ^2.0.8
  feedback: ^2.2.1 
  syncfusion_flutter_datepicker: ^19.4.38
  flutter_local_notifications: ^9.1.5
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.17
  flutter_phoenix: ^1.0.0
  date_picker_timeline: ^1.2.3  
  fluttericon: ^2.0.0
  fluttertoast: ^8.0.8

  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
  - family: MADType
    fonts:
    - asset: assets/fonts/Abel-Regular.ttf
  - family: Raleway
    fonts:
    - asset: assets/fonts/Raleway-Black.ttf
